[greeter]
theme-name     = Chicago95
icon-theme-name = Chicago95
font-name      = Sans 8
xft-antialias  = false
xft-hintstyle  = hintnone
cursor-theme-name = Chicago95 Cursor Black

# login panel: centered, fixed width, classic win95 dialog box look
position       = 50% 50%
panel-position = bottom

background     = #008080
hide-user-image = true
default-user-image = #icon-name=avatar-default

# clock in panel
indicators     = ~host;~spacer;~clock;~spacer;~session;~a11y;~power
clock-format   = %A, %B %-d, %Y  %-I:%M %p
